# Generated by Django 5.1.3 on 2024-11-14 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='warehouse.product')),
            ],
        ),
        migrations.CreateModel(
            name='DailyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_shifts', to='production.shift')),
            ],
        ),
        migrations.CreateModel(
            name='MachineUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_usages', to='production.dailyshift')),
                ('employees', models.ManyToManyField(related_name='machine_usages', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='production.machine')),
            ],
            options={
                'ordering': ['daily_shift__date'],
                'constraints': [models.UniqueConstraint(fields=('daily_shift', 'machine'), name='unique_dailyshift_machine'), models.CheckConstraint(condition=models.Q(('yield_amount__gte', 0)), name='positive_yield_amount')],
            },
        ),
    ]
